### ISSUE TITLE
help running with Duckdb

### ISSUE THREAD

**Issue by mapsgeek** [dbrest-io/dbREST#5]
i installed on windows and on linux subsystem and trying to set connection to duckdb using the following

```
dbrest conns set DUCKDB type=duckdb instance=/path to duckdb local file
```
i get error

```
fatal:
~
~ could not unset duckdb
~ could not write env file
~ could not write YAML file
```

**Comment by flarco** [comment]
Ah, that's strange. I'll take a look.
In the meantime, you can try using the env variables?
Like, open powershell and do `$env:DUCK='duckdb://C:/Temp/duck.db'`
For linux, it would be `export DUCK='duckdb:///tmp/duck.db'`
Then `dbrest conns list` and `dbrest conns test DUCK` should work

**Comment by flarco** [comment]
Release https://github.com/dbrest-io/dbREST/releases/tag/v0.0.68.
Should be good now!
